### PR TITLE
Datatables language

### PR DESCRIPTION
**Pull request by HB9HIL**
make the datatables available overall Cloudlog. 
Probably not the best solution but for the moment it seems okay for me.

### CODE REVIEW

**Comment by HB9HIL** [comment]
@Tamh 

Please update your `dev` branch before merging this. Your branch seems like not up to date

**Comment by Tamh** [comment]
We updated the PR to add some fixes to translation strings, and I pulled from the original `dev` branch.

Also, I like how the DataTables "patch" looks better this way.

The underlying issue, after I gave some thought to it, is that the language in Cloudlog is handled by a full string, instead of the more well-known ISO 639-1 codes, that could be leveraged to pull the DataTables translation files, somehow.

If we can store a mapping from that full length string to the ISO codes, we could make this process easier too.

**Comment by HB9HIL** [comment]
> We updated the PR to add some fixes to translation strings, and I pulled from the original `dev` branch.
> 
> Also, I like how the DataTables "patch" looks better this way.
> 
> The underlying issue, after I gave some thought to it, is that the language in Cloudlog is handled by a full string, instead of the more well-known ISO 639-1 codes, that could be leveraged to pull the DataTables translation files, somehow.
> 
> If we can store a mapping from that full length string to the ISO codes, we could make this process easier too.

We can leave it for the moment I guess. I will discuss that in the team and we'll see how we want to handle it. It's just the one liners in general_lang.php. But this solutions seems better then renaming the libary files to "german", "english" and so on.  😆

**Comment by HB9HIL** [comment]
we now just have to add 

```
"language": {
	url: get_datatables_language()
}
```

to every datatable in cloudlog 🤣

**Comment by HB9HIL** [comment]
> is that the language in Cloudlog is handled by a full string

This is the Codeigniter which handles the language. What we could think of is renaming Cloudlog's language paths to ISO 639-1 codes

**Pull request closed without merging**
